feat: Add delete all done tasks
AY2324S1-CS2103T-T10-2/tp pull request #115
Opened 2023-10-31 09:07 UTC by m1oojv

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [ ] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [ ] Documentation Update

## Description

-   Add feature to delete all done tasks.

## Related Tickets & Documents

-   Related Issue #114 

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [ ] Yes
-   [ ] No, and this is why: 
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2023-10-31 14:12 UTC, jiakai-17 commented
Please do fix the CI before requesting a review.

2023-11-01 09:05 UTC, freshcabbage123 requested changes
lgtm in general just have some queries

2023-11-01 09:05 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/DeleteAllDoneCommand.java
> +        }
Would it be better abstraction to implement a deleteAllDoneTasks() method instead inside Model and ModelManager? Similar to how it was implemented for #90

2023-11-01 23:44 UTC, m1oojv commented on src/main/java/seedu/address/logic/commands/DeleteAllDoneCommand.java
> +        }
> I think the for loop can be replaced with an enhanced for loop. Something like `for (Task t : lastShownList)`

@jiakai-17 I tried this method, but then it kept on facing with the problem of index error , no element found . and the last marled done element kept on not being able to get deleted.  I suspect the problem is given how the list changes with each iteration of the loop, which is why only deleting from the back is works. 
 which is why i used this loop instead

2023-11-02 01:47 UTC, m1oojv commented on src/main/java/seedu/address/logic/commands/DeleteAllDoneCommand.java
> +        }
@freshcabbage123 
> Would it be better abstraction to implement a deleteAllDoneTask() method instead inside Model and ModelManager? Similar to how it was implemented for #90 and #77

Moved to Model Manager. thanks

2023-11-02 02:09 UTC, pra-navi commented on src/main/java/seedu/address/model/ModelManager.java
> +        requireNonNull(person);
This is repeated

2023-11-02 05:21 UTC, jiakai-17 approved these changes

2023-11-02 05:24 UTC, freshcabbage123 approved these changes

2023-11-02 05:25 UTC, merged