feat: Implement findAllTag command
AY2324S1-CS2103T-T10-2/tp pull request #117
Opened 2023-10-31 11:30 UTC by freshcabbage123

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [X] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [ ] Documentation Update

## Description

-  Added findAllTag command that shows the user all persons and tasks that matches ALL tags given by user's input
-  All keywords are checked for complete matching instead of partial matching
## Related Tickets & Documents

-   Related Issue #116 

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [X] Yes

## [optional] Are there any post deployment tasks we need to perform?

2023-10-31 11:50 UTC, freshcabbage123 commented
Please help to test this command out! I have tried to include all testcase scenarios i could think of at the moment

2023-10-31 12:30 UTC, jiakai-17 requested changes
Thanks for the changes, just some minor nits regarding code style and comments.

I have also tested and it works well. 👍

2023-10-31 12:30 UTC, jiakai-17 commented on src/main/java/seedu/address/model/person/PersonContainsAllTagsPredicate.java
> + * Tests that a {@code Person}'s {@code Tags} matches all the keywords given.
Minor nit about phrasing, as a Person with tags `[A], [B], [C]` will pass with keywords `A, B`.

Same applies for TCATP below.

```suggestion
 * Tests that a {@code Person} has {@code Tags} that matches all the keywords given.
```

2023-10-31 12:30 UTC, jiakai-17 commented on src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
> +        assertNotEquals(1, firstFindAllTagCommand);
I think the 2nd line is redundant.

2023-10-31 12:30 UTC, jiakai-17 commented on src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
> +        assertNotEquals(null, firstFindAllTagCommand);
Should swap the order of the arguments such that firstFindAllTagCommand comes first.

This is because assertNotEquals calls the `equals` method of the first argument (if it is not null)

2023-10-31 12:30 UTC, jiakai-17 commented on src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
> +        TaskContainsAllTagsPredicate taskPredicate = prepareTaskTagPredicate("invalidTag ");
I think the trailing space is unintentional and can be removed.

If it was intentional, I believe you should create another testcase to test it separately.

2023-10-31 12:30 UTC, jiakai-17 commented on src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
> +    }
Good that you made this! Perhaps we could abstract this into another file so that everyone else can use it also? 

(This can be done in v1.4, so not to worry)

2023-10-31 12:30 UTC, jiakai-17 commented on src/test/java/seedu/address/model/person/PersonContainsAllTagsPredicateTest.java
> +        assertNotEquals(null, firstPredicate);
Same issue here for PCATP and TCATP

2023-10-31 13:55 UTC, freshcabbage123 commented on src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
> +    }
@jiakai-17 Yep i agree it could be better abstracted cuz i used it too in FindTagCommandTest.java

Any suggestions where i should refactor it to? I had the same question in mind when i was implementing tests for findTag as well :')

2023-10-31 15:56 UTC, freshcabbage123 commented on src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
> +    }
@jiakai-17  I made two implementations to abstract out the aforementioned function.

First implementation/commit e0d1c2a would be just to place it within the current AddressBookBuilder.

Upon further thinking, I believe that implementing a new TypicalAddressBook  might be more aligned to our current codebase as we already have builders for Task and Person as well as TypicalTasks and TypicalPersons.

As such, I believe the second implementation/commit ddf5435 may be a better solution. wdyt?

2023-11-01 04:39 UTC, jiakai-17 commented on src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
> +    }
I think the second would be good. 

Also, we should refactor the typicalAddressBook methods in the TypicalPersons and TypicalTasks also as it could be confusing. https://github.com/AY2324S1-CS2103T-T10-2/tp/blob/master/src/test/java/seedu/address/testutil/TypicalPersons.java#L65

So there could be three methods:
- addressbook with typical persons only
- addressbook with typical tasks only
- addressbook with both typical persons and typical tasks

However, this would require significant changes to the testing code, and in view of the 1.3 deadline, I think it would better to push it to 1.4 (as I believe this counts as improving tests, which is allowed)

2023-11-01 05:30 UTC, freshcabbage123 commented on src/test/java/seedu/address/logic/commands/FindAllTagCommandTest.java
> +    }
> So there could be three methods:
> 
> * addressbook with typical persons only
> * addressbook with typical tasks only
> * addressbook with both typical persons and typical tasks

@jiakai-17 okay so can we go with the second implementation here for findAllTag in 1.3, then in 1.4 we continue with the rest of refactoring? Since in 1.4 this will involve refactoring test code for other commands.

2023-11-01 05:35 UTC, jiakai-17 approved these changes

2023-11-01 08:13 UTC, HugeNoob requested changes

2023-11-01 08:13 UTC, HugeNoob commented on src/test/java/seedu/address/testutil/TypicalAddressBook.java
> +        return ab;
```suggestion
        AddressBook ab = new AddressBook();
        ab.setPersons(getTypicalPersons());
        ab.setTasks(getTypicalTasks());
        return ab;
```

Since `getTypicalPersons()` returns a `List<Person>`, you can make use of predefined methods in `AddressBook` class to abstract away the logic here.

2023-11-01 14:02 UTC, HugeNoob approved these changes

2023-11-01 14:02 UTC, merged