feat: Implement addTagTask and addTagPerson commands
AY2324S1-CS2103T-T10-2/tp pull request #118
Opened 2023-10-31 11:57 UTC by pra-navi

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [X] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [ ] Documentation Update

## Description

-   This feature allows users to add tags on top of the current list of tags.

## Related Tickets & Documents

-   Related Issue #113 

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [X] Yes
-   [ ] No, and this is why: _please replace this line with details on why tests
        have not been included_
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2023-10-31 14:08 UTC, jiakai-17 requested changes
Thanks for the changes. Just some nits about missing tests and naming

2023-10-31 14:08 UTC, jiakai-17 commented on src/test/java/seedu/address/logic/parser/AddTagPersonCommandParserTest.java
> +package seedu.address.logic.parser;
Missing tests for AddTagTaskCommandParser

2023-10-31 14:08 UTC, jiakai-17 commented on src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> +                        + INDEX_FIRST.getOneBased() + " " + " t/class");
Is the extra space intentional?

2023-11-01 08:41 UTC, HugeNoob submitted a review, later dismissed

2023-11-01 08:41 UTC, HugeNoob commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +        Person editedPerson = createEditedPerson(personToEdit, tagsToAdd);
I don't think we should couple code logic like this. Could you avoid using createEditedPerson to perform this operation? This feels like an unnecessary dependency.

2023-11-01 09:48 UTC, HugeNoob commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +        Person editedPerson = createEditedPerson(personToEdit, tagsToAdd);
Nvm I thought this was from `EditPersonCommand`

2023-11-01 12:00 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/parser/AddTagPersonCommandParser.java
> + * Parses input arguments and creates a new AddTagPersonCommand object
```suggestion
 * Parses input arguments and creates a new AddTagPersonCommand object.
```

2023-11-01 12:06 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/AddTagTaskCommand.java
> +    private final Set<Tag> tagsToAdd;
It is a little challenging to follow the tag related variables in this class. May i clarify if `oldTags` refer to the tags from user's input which are not going to be added? At first glance, it may give off the impression that these tags refer to the Person's current/existing tags.

2023-11-01 12:16 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +    private final Set<Tag> tagsToAdd;
same query as that in AddTagTaskCommand. perhaps comments before variable naming could help in this case?

2023-11-01 12:17 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +                oldTags.add(tag);
My confusion originated from here as I would have thought that `oldTags` was same as `existingTags`.

2023-11-01 12:21 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +            return false;
Consider adding a test for this line as it's currently not tracked by code coverage. Perhaps you could do 
`assertFalse(instanceOfAddTagPersonCommand.equals(1));` in your test code.

2023-11-01 12:23 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/AddTagTaskCommand.java
> +            + ": Adds new tag to the task identified "
```suggestion
            + ": Adds new tags to the task identified "
```

Perhaps this should be plural as the javadoc and `MESSAGE_EDIT_TASK_SUCCESS` also refer to tags in plural?

2023-11-01 12:24 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +            + ": Adds new tag to the person identified "
```suggestion
            + ": Adds new tags to the person identified "
```

Similar comment in AddTagTaskCommand

2023-11-01 12:26 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/AddTagTaskCommand.java
> +            + PREFIX_TAG + "class";
```suggestion
            + PREFIX_TAG + "class" + " " + PREFIX_TAG + "assignee";
```

Perhaps this could better show user that this command accepts multiple tags?

2023-11-01 12:27 UTC, freshcabbage123 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +            + PREFIX_TAG + "catering";
```suggestion
            + PREFIX_TAG + "catering" + " " + PREFIX_TAG + "dining";
```
Similar comment in AddTagTaskCommand

2023-11-01 13:25 UTC, jiakai-17 requested changes

2023-11-01 13:25 UTC, jiakai-17 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +    private static Set<Tag> oldTags = new HashSet<>();
Should these variables be static?

2023-11-01 13:25 UTC, jiakai-17 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +            if (existingTags.contains(tag)) {
Perhaps you could use the `removeAll` and `retainAll` methods provided by the Set interface instead of a for loop?

https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#retainAll-java.util.Collection-

2023-11-01 13:25 UTC, jiakai-17 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +                    .collect(Collectors.joining(", "));
I think there is no need to explicitly declare a variable here, can just return the stream result.

2023-11-01 13:25 UTC, jiakai-17 commented on src/main/java/seedu/address/logic/parser/AddTagPersonCommandParser.java
> +        if (tags.size() == 0) {
```suggestion
        if (tags.isEmpty()) {
```

2023-11-01 13:26 UTC, jiakai-17 commented on src/main/java/seedu/address/logic/parser/AddTagTaskCommandParser.java
> +        if (tags.size() == 0) {
```suggestion
        if (tags.isEmpty()) {
```

2023-11-01 15:24 UTC, pra-navi commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +    private static Set<Tag> oldTags = new HashSet<>();
if i want to use addAll on oldTags, then yes (like later in the createEditedPerson) method

2023-11-02 00:26 UTC, pra-navi commented
> > Thanks for the changes! I suppose if we really wanted to we could test the assertion statements in `createEditedPerson` and `createEditedTask`. But I don't think it's a big deal and also didn't do it in previous PRs related to edit commands.
> 
> @pra-navi Adding on to this, is there any particular reason why you chose to use `assert` over `requireNonNull`?

Largely because I was basing it off EditPersonCommand which used assert as well, didn't see a point to change it if both works.

2023-11-02 04:11 UTC, jiakai-17 commented on src/main/java/seedu/address/logic/commands/AddTagPersonCommand.java
> +    private static Set<Tag> oldTags = new HashSet<>();
Do the other methods need to be static also? For example, what is the reasoning behind making the `createEditedPerson` method static?

2023-11-02 05:11 UTC, jiakai-17 approved these changes

2023-11-02 05:11 UTC, merged