docs: Add HugeNoob profile picture
AY2324S1-CS2103T-T10-2/tp pull request #21
Opened 2023-09-25 08:24 UTC by HugeNoob

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [ ] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [x] Documentation Update

## Description

Add my face.

## Related Tickets & Documents

-   Related Issue #

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [ ] Yes
-   [x] No, and this is why: can't test this
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2023-09-25 08:25 UTC, pra-navi approved these changes
LGTM

2023-09-25 11:03 UTC, jiakai-17 requested changes
LGTM, but according to the [2103T website](https://nus-cs2103-ay2324s1.github.io/website/schedule/week7/project.html), the various headings still need to be included, though placeholders can be used for the content.

Perhaps you could add back the headers?

2023-09-25 11:27 UTC, HugeNoob commented on docs/team/hugenoob.md
> +To be added soon. Stay tuned!
Done, [check it out](https://docs-hugenoob-website-docs.coordimate.pages.dev/team/hugenoob).

2023-09-25 11:37 UTC, jiakai-17 commented on docs/team/hugenoob.md
> +To be added soon. Stay tuned!
LGTM, thanks for the changes.

2023-09-25 11:37 UTC, jiakai-17 approved these changes

2023-09-25 11:43 UTC, pra-navi submitted a review, later dismissed

2023-09-25 11:54 UTC, pra-navi commented
LGTM, but should we standardise the format of team/name.md to follow the example given under this module (essentially jiakai's version)

2023-09-25 11:57 UTC, HugeNoob commented
> LGTM, but should we standardise the format of team/name.md to follow the example given under this module (essentially jiakai's version)

The format to follow is specified in the [CS2103T website](https://nus-cs2103-ay2324s1.github.io/website/schedule/week7/project.html#ppp-format-2).
![image](https://github.com/AY2324S1-CS2103T-T10-2/tp/assets/65714641/c54af7a4-3abf-430f-b185-0c3e92a5cc25)

2023-09-26 08:34 UTC, pra-navi approved these changes
LGTM!

2023-09-26 12:43 UTC, merged