docs: Add AboutUs page and PPP for Pranavi
AY2324S1-CS2103T-T10-2/tp pull request #44
Opened 2023-09-25 14:19 UTC by pra-navi

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [ ] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [X] Documentation Update

## Description

-   Describe your changes.

## Related Tickets & Documents

-   Related Issue #

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [ ] Yes
-   [X] No, and this is why: [https://pra-navi.github.io/tp/](url)
        have not been included_
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2023-09-25 14:42 UTC, HugeNoob requested changes

2023-09-25 14:42 UTC, HugeNoob commented on docs/team/pra-navi.md
> +* **Code contributed**: [RepoSense link](https://nus-cs2103-ay2324s1.github.io/tp-dashboard/?search=jiakai-17&breakdown=true)
```suggestion
* **Code contributed**: [RepoSense link](https://nus-cs2103-ay2324s1.github.io/tp-dashboard/?search=pra-navi&breakdown=true)
```

Hmm you don't seem to be jiakai-17 🤔

2023-09-25 14:42 UTC, HugeNoob commented on docs/team/pra-navi.md
> +        * Added Admonitions to User Guide [\#2](https://github.com/AY2324S1-CS2103T-T10-2/tp/pull/2)
Cmiiw but this is Jiakai's addition right? Remember to change it to yours instead.

2023-09-25 14:45 UTC, HugeNoob commented
Also, the link in your description seems to be broken.

2023-09-25 15:27 UTC, HugeNoob approved these changes

2023-09-26 04:24 UTC, HugeNoob requested changes

2023-09-26 04:24 UTC, HugeNoob commented on docs/DeveloperGuide.md
> +| `*`      | user with many persons in the address book | sort persons by name               | locate a person easily                                                            |
These changes are not relevant to this PR. Would be good if you can place these in a branch instead.

2023-09-26 04:24 UTC, HugeNoob commented on docs/team/pra-navi.md
> +    * Some parts of the history feature I added was adopted by several other class mates: To be added soon!
```suggestion
    * Forum issues that I have participated in can be found [here](https://github.com/nus-cs2103-AY2324S1/forum/issues?q=is%3Aissue+commenter%3Apra-navi+).    
    * Reported bugs and suggestions for other teams in the class: To be added soon!
    * Some parts of the history feature I added was adopted by several other class mates: To be added soon!
```

You're missing a line break for the "Reported bugs..." bullet point.
![image](https://github.com/AY2324S1-CS2103T-T10-2/tp/assets/65714641/b4f85b86-0877-4b21-8f30-930d9b0d2840)

2023-09-26 13:17 UTC, HugeNoob approved these changes

2023-09-26 13:18 UTC, jiakai-17 approved these changes

2023-09-26 13:19 UTC, merged