docs: Update Developer Guide with user profile and value proposition
AY2324S1-CS2103T-T10-2/tp pull request #54
Opened 2023-09-26 07:17 UTC by jiakai-17

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [ ] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [x] Documentation Update

## Description

* Add admonitions
* Add user profile and value proposition
* Update Glossary

## Related Tickets & Documents

-   Partially resolves #39 

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [ ] Yes
-   [x] No, and this is why: See deployment on https://docs-developer-guide-v1-1.coordimate.pages.dev/DeveloperGuide
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2023-10-04 07:51 UTC, HugeNoob requested changes
LGTM in general except the few changes I pointed out. 

Could you also list the exact additions you made to the Use Cases? Would make it easier to track and possibly resolve conflicts later. Thanks!

2023-10-04 07:51 UTC, HugeNoob commented on docs/DeveloperGuide.md
> +Use case ends.
```suggestion
  Use case ends.
```

Could you change this indentation to 2 spaces instead? I think it should be on the same level as the numbering. Same for the rest of your additions.

For reference, the 2a "use case ends" seems to be the correct indentation level.
![image](https://github.com/AY2324S1-CS2103T-T10-2/tp/assets/65714641/94a14720-3137-48a3-bfc5-4365ca5c2625)

2023-10-04 07:51 UTC, HugeNoob commented on docs/DeveloperGuide.md
> +
Nit: Can we end all points with a full stop?

![image](https://github.com/AY2324S1-CS2103T-T10-2/tp/assets/65714641/dbeae263-c35a-4c84-ae38-7ccbeccebefa)

2023-10-04 09:40 UTC, jiakai-17 commented on docs/DeveloperGuide.md
> +Use case ends.
Thank you for your comment, I have resolved them in https://github.com/AY2324S1-CS2103T-T10-2/tp/pull/54/commits/7fab60394bd49a01cae2ce884f25de0b3d5941b0.

2023-10-04 09:41 UTC, jiakai-17 commented on docs/DeveloperGuide.md
> +
Thank you for your comment, I have resolved them in https://github.com/AY2324S1-CS2103T-T10-2/tp/pull/54/commits/7fab60394bd49a01cae2ce884f25de0b3d5941b0.

2023-10-04 11:04 UTC, HugeNoob commented on docs/DeveloperGuide.md
>  * **Private contact detail**: A contact detail that is not meant to be shared with others
Do you think we should define MSS as well? 🤔

2023-10-04 13:19 UTC, pra-navi requested changes

2023-10-04 13:19 UTC, pra-navi commented on docs/DeveloperGuide.md
> +| `* * *`  | user                                       | add a new person                   |                                                                       |
What is this difference between user and event planner for? Should we standardise to just user? This might cause confusion for different levels of access.

2023-10-05 04:00 UTC, freshcabbage123 approved these changes
Thanks for formatting for the team!

2023-10-05 04:08 UTC, HugeNoob approved these changes

2023-10-05 04:08 UTC, merged