docs: Update User Guide for findPerson and findTask
AY2324S1-CS2103T-T10-2/tp pull request #60
Opened 2023-10-03 14:59 UTC by jiakai-17

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [ ] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [x] Documentation Update

## Description

* Add command format, notes, examples and screenshots
* Replace some admonitions
* Remove placeholder code

## Related Tickets & Documents

-   Related Issue #38 

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [ ] Yes
-   [x] No, and this is why: See deployment: https://docs-jiakai-user-guide-v1-1.coordimate.pages.dev/DraftUserGuide
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2023-10-04 13:26 UTC, HugeNoob requested changes

2023-10-04 13:26 UTC, HugeNoob commented on docs/DraftUserGuide.md
> +findPerson KEYWORD [KEYWORDS]…
I actually think `MORE_KEYWORDS` is better. Makes it clear that this isn't a typo.

2023-10-04 13:26 UTC, HugeNoob commented on docs/DraftUserGuide.md
> +findTask t/KEYWORD [KEYWORDS]… [n/KEYWORD [KEYWORDS]…]
As discussed, perhaps we can reduce the work by collapsing this functionality to search through title and docs together.

Remember to change the documentation below to match the changes.

2023-10-04 13:26 UTC, HugeNoob commented on docs/images/output/findTask_success.png
Would be good if you match the images to the examples you listed.

2023-10-04 14:48 UTC, freshcabbage123 approved these changes
Looks good, thank you for factoring in the suggested changes!

2023-10-04 14:51 UTC, m1oojv approved these changes
LGTM nice job

2023-10-05 11:11 UTC, jiakai-17 commented
Superseded by #70

2023-10-05 11:11 UTC, closed without merging