feat: Implement listPerson command
AY2324S1-CS2103T-T10-2/tp pull request #82
Opened 2023-10-15 18:46 UTC by freshcabbage123

## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [X] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [ ] Documentation Update

## Description

-   Replaced instances of `list` with `listPerson`

## Related Tickets & Documents

-   Related Issue #51 

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [X] Yes
-   [ ] No, and this is why: _please replace this line with details on why tests
        have not been included_
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2023-10-16 04:08 UTC, jiakai-17 approved these changes
Looks like a simple find and replace. LGTM. 👍 😄

2023-10-17 04:10 UTC, HugeNoob requested changes
LGTM in general. Small nits on comments and variable naming.

2023-10-17 04:10 UTC, HugeNoob commented on src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
>   * Contains integration tests (interaction with the Model) and unit tests for ListCommand.
```suggestion
 * Contains integration tests (interaction with the Model) and unit tests for ListPersonCommand.
```
Perhaps you can change this comment.

2023-10-17 04:10 UTC, HugeNoob commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +        assertCommandSuccess(listCommand, ListPersonCommand.MESSAGE_SUCCESS, model);
```suggestion
        String listPersonCommand = ListPersonCommand.COMMAND_WORD;
        assertCommandSuccess(listPersonCommand, ListPersonCommand.MESSAGE_SUCCESS, model);
```
For clarity and consistency, perhaps it would be good to rename this as well.

2023-10-18 08:44 UTC, merged