feat: Load and Store Task statuses
AY2324S1-CS2103T-T10-2/tp pull request #92
Opened 2023-10-19 01:55 UTC by jiakai-17

## What type of PR is this? (check all applicable)

-   [x] Refactor
-   [x] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [ ] Documentation Update

## Description

-   Implement ability to load and store the completion status of a Task.
- Also cleaned up formatting of test JSON files.

## Related Tickets & Documents

-   Related Issue #

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [x] Yes
-   [ ] No, and this is why: _please replace this line with details on why tests
        have not been included_
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2023-10-19 13:58 UTC, freshcabbage123 reviewed
Thanks for the changes, just have some minor clarification

2023-10-19 13:58 UTC, freshcabbage123 commented on src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
> +        JsonAdaptedTask invalidTaskTitle = new JsonAdaptedTask(INVALID_TITLE, VALID_NOTE, false);
Nit: I understand that the `false` here represents the status of the `isDone` variable in an JsonAdaptedTask instance. Would it improve readability if the boolean variables were named as constants in a similar way as `EMPTY_TITLE` and `VALID_NOTE`, wdyt?

2023-10-20 03:42 UTC, HugeNoob requested changes

2023-10-20 03:42 UTC, HugeNoob commented on src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
> +        JsonAdaptedTask invalidTaskTitle = new JsonAdaptedTask(INVALID_TITLE, VALID_NOTE, false);
I feel that it would be good if you could use the `Status.TaskStatus` enum values instead of boolean true / false.

It would be a more extensible design, if we choose to add new task statuses in the future.

2023-10-20 04:06 UTC, HugeNoob commented on src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
> +        JsonAdaptedTask invalidTaskTitle = new JsonAdaptedTask(INVALID_TITLE, VALID_NOTE, false);
Nvm I guess we can keep it as a boolean for now.

2023-10-20 04:09 UTC, HugeNoob approved these changes

2023-10-20 04:14 UTC, freshcabbage123 approved these changes
Thanks for the changes, I suppose the task status is clear for now without enums

2023-10-20 04:14 UTC, merged